### PR TITLE
fix: fixing default value for ic-admin-version

### PR DESCRIPTION
**Pull request by NikolaMilosa**

### CODE REVIEW

**Review by LittleChimera — APPROVED** [review]

**Review by DFINITYManu — CHANGES_REQUESTED** [review]
I tried the URL with from-governance and yeah, it is 403.  If the code was interpolating FromGovernance into a string, and now it is interpolating from-governance, that's never gonna work.

Did you test this?

**Comment by NikolaMilosa** [comment]
Of course, did you?

**Review by DFINITYManu — APPROVED** [review]
Now I have.  It works.  How can this fix the issue??

**Comment by DFINITYManu** [comment]
Ah I see:

```

impl From<&str> for IcAdminVersion {
    fn from(value: &str) -> Self {
        match value {
            "from-governance" | "governance" | "g" | "govn" => Self::FromGovernance,
            "default" | "d" => Self::Default,
            s => Self::Strict(s.to_string()),
        }
    }
}
```

**Pull request merged**
